name: specfem_tomo_helper
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - pyproj
  - pandas
  - cartopy
  - netCDF4
  - jinja2
  - ruamel.yaml
  - requests
  - scikit-learn
  - matplotlib
  - pip:
    - -e .
    # Optional:
    # for transforming anisotropic models to the specfem3d_cartesian basis
    #- git+https://github.com/uafgeotools/elasticmapper.git
